### ISSUE TITLE
Error:(data.linz.govt.nz) Not Found

### ISSUE THREAD

**Issue by jcm36** [linz/linz-data-importer#80]
Hi,

Firstly, thanks for such a great plugin!

However, over the last few days my colleagues and I keep getting "Error:(data.linz.govt.nz) Not Found" when opening the plugin.

Screenshot attached. 

Do you know what could be causing this?

Thanks
![Error](https://user-images.githubusercontent.com/9682969/95784906-3d6c5300-0d31-11eb-9dd5-cb7adf6c499a.png)

**Comment by SPlanzer** [comment]
Thanks for opening the issue @jcm36 

This is a new one so no tested solution. If you can provide details for getting it into this state we can write a solution and tests. 

For now could you either 
* go to the "settings" tab in the UI and delete your API key(s) and re-add them 
* Alternatively run `Settings().setValue('linz_data_importer/apikeys', {})` in the qgis python console (will also remove all api keys) and re add them via the ui

you can also run `QSettings().value('linz_data_importer/apikeys')` to ensure there are no keys stored (should return an empty dict)

Please let me know if this does not resolve the issue.

**Comment by jcm36** [comment]
I just deleted my API key, generated a new one, and re-added it back in, but I'm still getting the same error.

As a test, I set up a manual connection for the LINZ Topo50 WMTS using my API key, and it was able to connect and add the Topo50 basemap to my project.

Let me know if there are any log etc that I could send you.

Thanks,

**Comment by SPlanzer** [comment]
Im stumped. Could you please remove the keys and uninstall/reinstall the plugin

**Comment by jcm36** [comment]
Just tried that, but no luck. I still get the same error.

I noticed the following lines in my Python Warnings log.  Do they help at all?

` warning:C:\OSGEO4~1\apps\Python37\lib\site-packages\owslib\wmts.py:803: UserWarning: The 'tilematrixsets' attribute has been deprecated and will be removed in a future version of OWSLib. Please use 'tilematrixsetlinks' instead.
              warnings.warn("The 'tilematrixsets' attribute has been deprecated"
             
             traceback: File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\linz-data-importer\linz_data_importer.py", line 433, in run
              self.loadUi()
              File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\linz-data-importer\linz_data_importer.py", line 461, in loadUi
              load_data_err=self.loadAllServices()
              File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\linz-data-importer\linz_data_importer.py", line 497, in loadAllServices
              service_data_instance.processServiceData()
              File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\linz-data-importer\service_data.py", line 335, in processServiceData
              self.formatForUI()
              File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\linz-data-importer\service_data.py", line 406, in formatForUI
              self.crs = dataset_obj.tilematrixsets
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\owslib\wmts.py", line 803, in tilematrixsets
              warnings.warn("The 'tilematrixsets' attribute has been deprecated"`

**Comment by strk** [comment]
@jcm36 was the manual connection still done via the same QGIS instance that was triggering the "Not Found" error ? Did QGIS version or this plugin's version changed between when you saw it working and when you started getting the error ?

**Comment by jcm36** [comment]
I've tried in the same QGIS instance, a fresh instance, after a restart etc and still the same thing.

If I get a chance later today I'll do a full clean install of QGIS and the plugin and see if that fixes the issue.

**Comment by strk** [comment]
Did that work ? Can it have to do with proxy ?

**Comment by jcm36** [comment]
Sorry, haven't had a chance to do a full uninstall / reinstall of everything just yet.

We're not using any proxies etc, and it seems odd that  I can still add the WMTS manually still.

**Comment by DJIDan** [comment]
I am also having the same issues since this was first posted - Was happening on LTS (was working previously) and has not worked on 3.16.

Fresh install on Ubuntu for both, also happening on fresh installs for Windows.

I can see that it is pulling the wmts XML list of data into my app folder

AttributeError: 'LinzDataImporter' object has no attribute 'data_type' 
Traceback (most recent call last):
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 718, in importDataset
    if not self.layers_loaded and not self.data_type == 'table':
AttributeError: 'LinzDataImporter' object has no attribute 'data_type'


Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0] 

As a work around I have manually added the WTMS link with the API get as a full string

https://data.linz.govt.nz/services%3Bkey%3D<YOURAPIKEY>/wmts/1.0.0/WMTSCapabilities.xml

**Comment by SPlanzer** [comment]
Thanks you @DJIDan this is very useful information. 

We will us this to investigate further

**Comment by jcm36** [comment]
I updated to QGIS 3.16 today (haven't had a chance to clean install), and the error still occurs.

Please let me know if there is anyway I can help (providing logs, or testing etc) @SPlanzer 

Thanks,

**Comment by SPlanzer** [comment]
As a starting point I am looking to release the version currently in dev that removes WMS asap as this version does not contain this behavior (therefore is this an issue with WMS turned off and how the current version handles this?)

Any bug fixing required will then be understood and resolved against this release
ETA for release 1-2 days

**Comment by jcm36** [comment]
I've just updated to the latest version of the plugin, and can confirm it's fully functional and working again.  

Thanks for the great work looking into and fixing this.  Cheers,

**Comment by SPlanzer** [comment]
@jcm36 @DJIDan I have released a new version that we have had planned for release for sometime. It does not specifically target your issue but does potentially explain why I did not see this issue myself (as I have been using the development version) 

The new version removes WMS as our server no longer supports this. Could you please upgrade to this version (v2.1.0-beta) and let me know if you still have issues. 
Cheers

**Comment by SPlanzer** [comment]
>  I've just updated to the latest version of the plugin, and can confirm it's fully functional and working again.
>
> Thanks for the great work looking into and fixing this. Cheers,

Thanks heaps for reporting this in the first place. without these reports we do not know to fix such issues

**Comment by DJIDan** [comment]
Confirmed to be working on my end too. Thanks for sorting this one out.
Dan Morton
Commercial and Technical Manager
DJI Certified Engineer
ferntechcommercial.co.nz <http://www.ferntechcommercial.co.nz>

*Take a look at our latest aerial LiDAR solution
<https://www.ferntechcommercial.co.nz/lidar-systems>*

**Comment by SPlanzer** [comment]
Great. Closing
